-- 1. 创建 profiles 表 (扩展 auth.users)
create table profiles (
  id uuid references auth.users on delete cascade not null primary key,
  name text,
  role text default 'user',
  credits int default 3,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. 创建 templates 表
create table templates (
  id bigint generated by default as identity primary key,
  title text,
  prompt text,
  aspect_ratio text,
  image_url text, -- 存储 Storage 的公开链接
  reference_image text, -- 存 Base64 方便点，或者也存 Storage
  author text,
  owner_id uuid references auth.users,
  is_published boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. 开启存储 Bucket
insert into storage.buckets (id, name, public) values ('images', 'images', true);

-- 4. 简单的 RLS 策略 (为了演示方便，允许公开读取，仅允许所有者写入)
alter table profiles enable row level security;
create policy "Public profiles" on profiles for select using (true);
create policy "Users can update own profile" on profiles for update using (auth.uid() = id);
-- 添加 insert 策略：允许插入（主要用于 admin client 创建 profile）
-- 注意：由于使用 admin client (SERVICE_ROLE_KEY)，理论上可以绕过 RLS，但添加策略可以确保兼容性
create policy "Allow profile creation" on profiles for insert with check (true);

alter table templates enable row level security;
create policy "Public templates" on templates for select using (true);
create policy "Users can insert templates" on templates for insert with check (auth.uid() = owner_id);

-- 允许未登录用户上传图片到 Storage (为了简化流程，实际生产需更严谨)
create policy "Public Access" on storage.objects for select using ( bucket_id = 'images' );
create policy "Auth Upload" on storage.objects for insert with check ( bucket_id = 'images' );